/*
 * generated by Xtext
 */
package unifi.marcotinacci.thesis.seal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SealUiModule extends unifi.marcotinacci.thesis.seal.ui.AbstractSealUiModule {
	public SealUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
