/*
* generated by Xtext
*/
package unifi.marcotinacci.thesis.seal.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SealOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
