/*
* generated by Xtext
*/
package unifi.marcotinacci.thesis.seal;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SealUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return unifi.marcotinacci.thesis.seal.ui.internal.SealActivator.getInstance().getInjector("unifi.marcotinacci.thesis.seal.Seal");
	}
	
}
