/*
 * generated by Xtext
 */
package unifi.marcotinacci.thesis.seal;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SealRuntimeModule extends unifi.marcotinacci.thesis.seal.AbstractSealRuntimeModule {

}
