/*
 * generated by Xtext
 */
package unifi.marcotinacci.thesis.seal.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import unifi.marcotinacci.thesis.seal.ui.internal.SealActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SealExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SealActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SealActivator.getInstance().getInjector(SealActivator.UNIFI_MARCOTINACCI_THESIS_SEAL_SEAL);
	}
	
}
