/*
* generated by Xtext
*/
package unifi.marcotinacci.thesis.seal.ui.contentassist;

import unifi.marcotinacci.thesis.seal.ui.contentassist.AbstractSealProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SealProposalProvider extends AbstractSealProposalProvider {

}
