/*
* generated by Xtext
*/
package unifi.marcotinacci.thesis.seal.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import unifi.marcotinacci.thesis.seal.services.SealGrammarAccess;

public class SealParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SealGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected unifi.marcotinacci.thesis.seal.parser.antlr.internal.InternalSealParser createParser(XtextTokenStream stream) {
		return new unifi.marcotinacci.thesis.seal.parser.antlr.internal.InternalSealParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public SealGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SealGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
