/*
* generated by Xtext
*/
package unifi.marcotinacci.thesis.seal.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SealAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("unifi/marcotinacci/thesis/seal/parser/antlr/internal/InternalSeal.tokens");
	}
}
